blank_issues_enabled: false
contact_links:
  - name: 📚 Ver el ranking de apuntes
    url: https://chocolate-44.github.io/Repositorio-carrera-de-estadistica-UCR/
    about: Página con los apuntes ordenados por puntuación.
